name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests and generate report
        run: |
          cd tests
          mkdir -p reports
          pytest t_login_page.py --browser=chrome --html=reports/reports.html
        continue-on-error: true  # This ensures the workflow continues even if pytest fails

      - name: List files in reports folder
        run: ls -alh tests/reports/

      - name: Show test results in logs
        if: failure()
        run: cat tests/reports/reports.html  # or you can log key parts

      - name: Set output
        id: results
        run: echo "artifactPath=tests/reports/" >> $GITHUB_OUTPUT

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: tests/reports/

      - name: Notify on failure
        if: failure()  # This step will run only if the previous steps failed
        run: echo "Test failed. Please check the logs or the HTML report for more details."
